// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type IpLog struct {
	ID          int32          `json:"id"`
	IpAddress   string         `json:"ip_address"`
	Country     sql.NullString `json:"country"`
	Region      sql.NullString `json:"region"`
	City        sql.NullString `json:"city"`
	Latitude    sql.NullString `json:"latitude"`
	Longitude   sql.NullString `json:"longitude"`
	UserAgent   sql.NullString `json:"user_agent"`
	Referrer    sql.NullString `json:"referrer"`
	RequestTime sql.NullTime   `json:"request_time"`
}
